### ISSUE TITLE
Resolution and Passwords Not Saving in Connection Profiles

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/Remmina#1307]
In Ubuntu 16.04.3, recent Remmina Next updates have disabled Remmina's ability to properly save user-prescribed resolution settings in connection profiles.

Saving [these settings](http://neartalk.com/ss/2017-10-10_003_859x640.png), to anything different than default, does not persist. Subsequent connection attempts will connect at 800X600 resolution instead of honoring the settings you've saved.

Additionally, one of my Remmina users has also reported that his passwords are not being saved properly on newly created Remmina connection profiles.

**Comment by giox069** [comment]
Are you using the ubuntu PPA or the SNAP version?

Resolution: I'm unable to reproduce the problem but please consider the following: if you enabled "dynamic resolution update" by pressing the following button (available only when connecting to win 8.1/server 2012R2 or newer)
![immagine](https://user-images.githubusercontent.com/5477803/31404839-80580ace-adfd-11e7-843d-3ecda09a5cef.png)
then the resolution file in the profile editor will not be used. Every new connection window will have the dynamic resolution setup the last time you used it.
Can you check if you are using dynamic resolution update?

Password not saved: maybe you did not install remmina-plugin-gnome on that pc? Check that passwords are stored on the gnome keyring by using the "seahorse" application.

Have you also checked that your remmina profile files are writeable? They are store under ~/.local/share/remmina directory.

PS: please also open two separate issue for two different problems. Do not use the same issue to ask two or more different problems.

**Comment by antenore** [comment]
Hi Lennie! Can you also tell us precisely wich remmina version?

Just to know as we have released yesterday a new version.

Thank you

**Comment by antenore** [comment]
My bad!!! You are right.

"Save & Connect" always work, but not "Save". Password are always stored on the other hand.

So, yes, this is a bug, in the meanwhile, can you please use "Save and Connect" till we won't fix it?

Thanks and sorry for this!

**Comment by Lonniebiz** [comment]
@giox069 : We are using the PPA in 16.04.3, installed like this:
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next ; sudo apt-get update ; sudo apt-get install remmina remmina-plugin-rdp

The "dynamic resolution update" is not enabled.

Sorry about mentioning two issue in one post, but both "passwords" and "resolution" are located very closely together on the profile form and both seem to have stop working at the time that the "save and connect" button was added to the profile-form. It seems like recent changes may have cause
certain form-elements to get by-passed during "save" and "save and connect".

@antenore : The version (in Menu > About) is 1.2.0-rcgit-21 (git rcgit-21). The user has demonstrated to me that the password does not save on both "save" button *and* "save and connect". The user actually sent me [this video](https://youtu.be/N2b77FOvh1g).

**Comment by antenore** [comment]
Closed via #1308

**Comment by Lonniebiz** [comment]
Resolution is still an issue, but I've reported that here:
https://github.com/FreeRDP/Remmina/issues/1323

I guess we should let this bug focus on the Password Saving issue?

I'm running 1.2.0-rcgit-22, and the password is saving for me.

However, I've verified that another user of mine is also running 1.2.0-rcgit-22, but it is **not** saving his password via **both** "save" and "save and connect". I've had this user delete and recreate his profile from scratch and we cannot get the profile to remember his password.

I cannot seem to figure out what is different between our two setups on 1.2.0-rcgit-22. Why would it save password for me, but when he does it, it does not save password?

giox069 mentioned something about the "dynamic resolution update" button being toggled, but the code should be written in a way were the save password is saved regardless of how any toggle buttons are set.

This is getting confusing.

**Comment by Lonniebiz** [comment]
My user, sent this video:
https://youtu.be/KPAS-oQYf2c

**Comment by giox069** [comment]
@Lonniebiz for this issue: resolution problem is tracked in the other issue and I hope is fixed.
For your user reporting password not saving, it could be an issue specific to your user. Update its remmina to the .23 version. Check if the package "remmina-plugin-gnome" is installed or not and let us know more details by opening a new issues (do not reuse this one).
