### ISSUE TITLE
VNC window immediately closes after connection attempt

### ISSUE THREAD

**Issue by ahow628** [FreeRDP/Remmina#699]
I started using Remmina about 3 years ago and it worked great. At some point (maybe two years ago), it began to immediately close when I started a session. At that point, I ended up removing Remmina and all of its config files and whatnot. I reinstalled, but still it did the same thing.

Now two years later, I tried the remmina-next PPA and it still does the same thing, so I'm hoping I can figure out the problem.

VNC Viewer and other VNC apps work fine.

Please let me know what I can test or any other logs I can provide.

Here is the debugging log:
```
[VNC]VNC server supports protocol version 3.8 (viewer 3.8)
[VNC]We have 1 security types to read
[VNC]0) Received security type 2
[VNC]Selecting security type 2 (0/1 in the list)
[VNC]Selected Security Scheme 2
[VNC]VNC authentication succeeded
[VNC]Desktop name "htpc-backend:0"
[VNC]Connected to VNC server, using protocol version 3.8
[VNC]VNC server default format:
[VNC]  32 bits per pixel.
[VNC]  Least significant byte first in each pixel.
[VNC]  TRUE colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
[VNC]client2server supported messages (bit flags)
[VNC]00: 00ff 0081 0000 0000 - 0000 0000 0000 0000
[VNC]08: 0000 0000 0000 0000 - 0000 0000 0000 0000
[VNC]10: 0000 0000 0000 0000 - 0000 0000 0000 0000
[VNC]18: 0000 0000 0000 0000 - 0000 0000 0000 0004
[VNC]server2client supported messages (bit flags)
[VNC]00: 001f 0080 0000 0000 - 0000 0000 0000 0000
[VNC]08: 0000 0000 0000 0000 - 0000 0000 0000 0000
[VNC]10: 0000 0000 0000 0000 - 0000 0000 0000 0000
[VNC]18: 0000 0000 0000 0000 - 0000 0000 0000 0004
[VNC]Connected to Server "unknown (LibVNCServer 0.9.9)"
[VNC]Tight encoding: JPEG is not supported in 8 bpp mode.
```

**Comment by antenore** [comment]
You are probably using an old Remmina version.

Please follow the wiki to update it and let me know if you still have any issues.

Thanks!

**Comment by jasmin-j** [comment]
Hi!

I have exactly the same issue.
I am running Linux Mint 17.1 on my main machine and I have x11vnc as VNC server running.
On my laptop I have Linux Mint 17.3. I added ppa:remmina-ppa-team/remmina-master and reinstalled remmina. Now I have 1.1.2 (by the way, the RDP plugin is gone now).

Here is the x11vnc log:
~~~
17/12/2015 01:00:06 Got connection from client 192.168.23.123
17/12/2015 01:00:06   other clients:
17/12/2015 01:00:06 Normal socket connection
17/12/2015 01:00:06 check_access: client 192.168.23.123 matches pattern 192.168.23.
17/12/2015 01:00:06 incr accepted_client=16 for 192.168.23.123:46573  sock=5
17/12/2015 01:00:06 Client Protocol Version 3.8
17/12/2015 01:00:06 Protocol version sent 3.8, using 3.8
17/12/2015 01:00:06 rfbProcessClientSecurityType: executing handler for type 2
17/12/2015 01:00:06 Pixel format for client 192.168.23.123:
17/12/2015 01:00:06   8 bpp, depth 8
17/12/2015 01:00:06   true colour: max r 7 g 7 b 3, shift r 0 g 3 b 6
17/12/2015 01:00:06 rfbProcessClientNormalMessage: ignoring unsupported encoding type ultraZip
17/12/2015 01:00:06 Using compression level 9 for client 192.168.23.123
17/12/2015 01:00:06 Using image quality level 0 for client 192.168.23.123
17/12/2015 01:00:06 Using JPEG subsampling 1, Q15 for client 192.168.23.123
17/12/2015 01:00:06 Enabling KeyboardLedState protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Enabling NewFBSize protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Enabling LastRect protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Enabling SupportedMessages protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Enabling SupportedEncodings protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Enabling ServerIdentity protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Enabling Xvp protocol extension for client 192.168.23.123
17/12/2015 01:00:06 Using tight encoding for client 192.168.23.123
17/12/2015 01:00:07 rfbSendUpdateBuf: write: Broken pipe
17/12/2015 01:00:07 client_count: 0
17/12/2015 01:00:07 Client 192.168.23.123 gone
~~~

I can connect to my main machine using Windows and a VNC Viewer there. So it is no problem on the server side. I can use remmina to connect to an Windows machine running a VNC server.

Is there any possibility so activate a debug log to get some information from the VNC Plugin or remmina itself?

BR
   Jasmin

**Comment by jasmin-j** [comment]
Changed now to the correct repo ppa:remmina-ppa-team/remmina-next (by the way, the RDP plugin is available now).
Now I have 1.2.0-rcgit6, but the problem still exists :(

**Comment by antenore** [comment]
From the Help menu you can open a Debug Window.

I think I've replicated your issue, in fact the VNC connections fails immediately.

What is see and guess it's that libvnc trys to connect to a inet6 address, instead of staying with tcp4

[VNC]ConnectClientToTcpAddr6: connect

Hopefully I should be able to fix this quite fast

**Comment by jasmin-j** [comment]
> From the Help menu you can open a Debug Window.

Found it, but it does not tell me much. Is there a debug level to increase?

> I think I've replicated your issue, in fact the VNC connections fails immediately.
> What is see and guess it's that libvnc trys to connect to a inet6 address, instead of staying with tcp4
> [VNC]ConnectClientToTcpAddr6: connect

Could be in your particular case, but in my log there isn't that line:
~~~
 [VNC]VNC server supports protocol version 3.8 (viewer 3.8)
 [VNC]We have 1 security types to read
 [VNC]0) Received security type 2
 [VNC]Selecting security type 2 (0/1 in the list)
 [VNC]Selected Security Scheme 2
 [VNC]VNC authentication succeeded
 [VNC]Desktop name "hoppel's Remote Desktop"
 [VNC]Connected to VNC server, using protocol version 3.8
 [VNC]VNC server default format:
 [VNC]  32 bits per pixel.
 [VNC]  Least significant byte first in each pixel.
 [VNC]  TRUE colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
 [VNC]client2server supported messages (bit flags)
 [VNC]00: 00ff 0081 0000 0000 - 0000 0000 0000 0000
 [VNC]08: 0000 0000 0000 0000 - 0000 0000 0000 0000
 [VNC]10: 0000 0000 0000 0000 - 0000 0000 0000 0000
 [VNC]18: 0000 0000 0000 0000 - 0000 0000 0000 0004
 [VNC]server2client supported messages (bit flags)
 [VNC]00: 001f 0080 0000 0000 - 0000 0000 0000 0000
 [VNC]08: 0000 0000 0000 0000 - 0000 0000 0000 0000
 [VNC]10: 0000 0000 0000 0000 - 0000 0000 0000 0000
 [VNC]18: 0000 0000 0000 0000 - 0000 0000 0000 0004
 [VNC]Connected to Server "unknown (LibVNCServer 0.9.9)"
 [VNC]Tight encoding: JPEG is not supported in 8 bpp mode.
~~~

> Hopefully I should be able to fix this quite fast

This might be one problem, but it seems I have another one. Maybe you could add more debug logging to track this further down. I don't know if there is a debug level implemented. In case there is, maybe you can add a possibility to increase that.

**Comment by antenore** [comment]
> [VNC]Tight encoding: JPEG is not supported in 8 bpp mode.  

This is the root of the problem, in fact, in my case, setting True Color I can connect to the server

Try yourself and let me know please.

![1d323ab96619fae2](https://cloud.githubusercontent.com/assets/5975/11865026/8e50e16c-a4a1-11e5-8b37-ca363347d23a.jpg)



> Maybe you could add more debug logging to track this further down. I don't know if there is a debug level implemented. In case there is, maybe you can add a possibility to increase that. 
 
Yes, this is something that has to be done. There is quite a lot of work to do with this plugin and will be something we will work on in the future. Hopefully someone will helping us contributing with some code?

**Comment by antenore** [comment]
Fixed in Remmina 1.2.0.rcgit.7

**Comment by jasmin-j** [comment]
> This is the root of the problem, in fact, in my case, setting True Color I can connect to the server
> Try yourself and let me know please.

I changed this in 1.2.0-rcgit6 version and it did the trick. It will now connect.
I will upgrade now to rcgit7.

THX!!!

**Comment by ahow628** [comment]
I switched to True Color and the heavens opened while angels were singing. This issue has been an annoyance for years now (given I had to use a crappier VNC client). Thanks for working on this issue so diligently and thank you to everyone for chiming in. I'm glad it is finally working for me.

**Comment by antenore** [comment]
I'm glad it worked. :-)

**Comment by ElectricRCAircraftGuy** [comment]
just installed the latest Remmina version (1.2.0-rcgit-15) and the default for VNC is still not 15-bit color. It is 8-bit color, and still has the bug where it crashes. I thought you were going to change the default to 15-bit color?

**Comment by ElectricRCAircraftGuy** [comment]
Also, side question: when I connect to a VNC server my Remmina menus used to be horizontal across the top, but now they are default vertical on the left side. I was able to drag them to be horizontal across the bottom, but I really want them horizontal across the top of the screen again. How can I change it to be like this?

**Comment by antenore** [comment]
With the current Remmina architecture, this change is quite complex to put in place.

Before to change the code and add other workarounds, I'm looking to improve the code.

Unlucky I don't have time in the next weeks, so if anybody wants to help, I can guide any volunteers in hacking the Remmina code.

**Comment by antenore** [comment]
BTW, this is a closed issue. @ElectricRCAircraftGuy can you please open a new issue for each problem?

Thanks in advance.
