### ISSUE TITLE
Impossible to NOT save password when connected

### ISSUE THREAD

**Issue by alex0x50** [FreeRDP/Remmina#807]
I need to connect to remore PC without saving password.

Environment:
- remmina in linux (ubuntu 14.04);
- changed default remmina option "Double-click action" => "Edit settings";
- connection via RDP using RD Gateway server (don't know if it's important) and with option "Disable password storing" enabled.
Repro steps:
- double click on connection => connection properties window is opened;
- type password;
- click "Connect" (connection must be succeeded);
- close remote session;
- double click on the same connection again;
Actual result: connection properties window is opened with stored (previously typed) password;
Expected result: connection properties window is opened with blank password field;

Additional information:
Earlier this options combination allowed to connect without storing password.
Since some time (suppose few weeks or months ago) password is always stored that is from my point of view is a bug.
Current version is 1.2.0-rcgit.10 (git n/a).
If it's possible to not save password and type it for every connection please let me know.
I googled if it's possible but search results were about different remmina password-related topics.

**Comment by giox069** [comment]
Hi @alex0x50.
This seems to be a regression bug after commit https://github.com/FreeRDP/Remmina/commit/4841912340f164d9ec3c1897def8aaf9f2bd6ebe
I'm marking it as a bug.

**Comment by metafarion** [comment]
This is still an issue as recently as 1.2.0-rc16, and it DOES appear to be related to the use of Remote Desktop Gateway; it still does not seem possible to connect to an RDP host via  Remote Desktop Gateway without having entered the password in the Profile screen first (and therefore saving it).

When connecting to an RDP host for which credentials have not yet been provided, we get a username/password prompt with a Save checkbox as expected.  When connecting via RDG, if no credentials have been provided for the gateway server, Remmina appears to simply attempt authentication without them which obviously fails every time.

Furthermore, Remmina does not appear to differentiate between RDP host credentials, and RDG credentials.  In many setups they are the same, but not always and the Windows Remote Desktop client definitely has the capability to input them separately (see link).
https://msdnshared.blob.core.windows.net/media/TNBlogsFS/prod.evol.blogs.technet.com/CommunityServer.Blogs.Components.WeblogFiles/00/00/01/02/40/r3.png

**Comment by antenore** [comment]
Rcgit-16 is really old. This issue has been fixed recently.
Can you please update Remmina following our wiki and test it again?

**Comment by metafarion** [comment]
Oh sorry, I should have paid more attention to the version numbers.  I figured rc16 couldn't be that old if OP was using rc10 as recently as last March.

Anyway, I'm using rc20 now, and RDP passwords are not being saved unless the box is checked in the login prompt.  So that's good.  However, RDG passwords do still appear to be saved regardless of specified settings.  Also, RDG credentials still need to be entered in the connection profile in advance; Remmina does not prompt for them at connection time if they haven't been; it simply attempts the connection without them and authentication fails.

The way the Windows client handles this is to prompt for RDG credentials if none have been specified, and also provide a "use same login/password for RDP host" checkbox to avoid making the user enter them twice.

**Comment by antenore** [comment]
@metafarion good point, I'll take a look. 
Do you have an RDP gateway I can use for tests?

Do you estimate this is a critical issue? My understanding is that you can work saving the passwords without any problems, except the fact that the password is stored in Remmina or in the keychain.

Just to know if I can work on this at my pace (slowly but surely)

**Comment by metafarion** [comment]
It's not **critical**, but in some cases it's part of a corporation's SOPs that you cannot store their server password on your machine, and therefore you'd have to delete the connection profile in Remmina and/or gnome keyring each time to be in compliance.  Anal retentive? Yes, but you can imagine why they'd have such a policy.

I'd be glad to haul out my testing Windows Server and give you access, or help in any other way I can.  I'm not a coder, but a fairly experienced sysadmin, and I've been working with Windows RDP/RDG for some time.

**Comment by metafarion** [comment]
A related recent discovery: If the RD Gateway credentials are saved in the connection profile but the RDP host credentials are not, then Remmina prompts the user for the password.  So far so good.  

HOWEVER, if the user enters an incorrect password in this prompt, the saved RD Gateway credentials are removed from the connection profile, resulting in a de-facto authentication failure on the next attempt.

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @alex0x50 @antenore @giox069 @metafarion
